version: '3.8'

services:
  web:
    build:
      context: ./track_separation
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - uploads_volume:/app/Uploads
      - output_volume:/app/output
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - app_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - app_network

  redis:
    image: redis:7
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
      - frontend
    networks:
      - app_network

volumes:
  postgres_data:
  static_volume:
  media_volume:
  uploads_volume:
  output_volume:

networks:
  app_network:
    driver: bridge