name: Build ZIP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: zip -r project.zip . -x ".git/*"

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-zip
          path: project.zip
