name: Build & Release ZIP

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP
        run: zip -r POZMUZ_2.0.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: POZMUZ_2.0.zip

